# Generated by Django 3.2.4 on 2021-06-22 12:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpage_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newflatpage',
            options={},
        ),
        migrations.RemoveField(
            model_name='newflatpage',
            name='content',
        ),
        migrations.AddField(
            model_name='newflatpage',
            name='content_section',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
    ]
