# Generated by Django 3.2.4 on 2021-06-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image_alt',
            field=models.CharField(default="Sorry, we're assholes and forgot to give you an image description.", max_length=200),
        ),
    ]
