# Generated by Django 3.2.4 on 2021-06-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_header_image'),
        ('blog', '0003_auto_20210611_1411'),
    ]

    operations = [
    ]
