# Generated by Django 3.2.4 on 2021-06-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210615_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_handle',
            field=models.CharField(blank=True, default='@open_apprentice', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_profile_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_handle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
