# Generated by Django 3.2.4 on 2021-06-15 23:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210615_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='short_bio',
            field=ckeditor.fields.RichTextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=ckeditor.fields.RichTextField(max_length=500, null=True),
        ),
    ]
