# Generated by Django 3.2.4 on 2021-06-15 23:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210616_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='short_bio',
            field=ckeditor.fields.RichTextField(max_length=200, null=True),
        ),
    ]
