# Generated by Django 3.2.4 on 2021-06-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='twitter_bio_handle',
            field=models.CharField(blank=True, default='@open_apprentice', help_text='Enter your bio details here.', max_length=255),
        ),
    ]
