# Generated by Django 3.2.4 on 2021-06-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_profile_twitter_bio_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='author_website',
            field=models.CharField(blank=True, default='https://ellieplatform.org', help_text='Enter your full website URL with https:// ', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_url',
            field=models.CharField(blank=True, help_text="Enter just your username, example, 'superbob'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram_handle',
            field=models.CharField(blank=True, default='@open_apprentice', help_text="Enter just your handle, example, 'superbob'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_profile_url',
            field=models.CharField(blank=True, help_text="Enter just your username, example, 'bobbarker'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter_bio_handle',
            field=models.CharField(blank=True, default='@open_apprentice', help_text="Enter just your handle, example, 'superbob'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='youtube_handle',
            field=models.CharField(blank=True, help_text="Enter just your username, example, 'bobbarker'.", max_length=255),
        ),
    ]
