# Generated by Django 3.2.4 on 2021-06-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210616_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='author_website',
            field=models.CharField(blank=True, default='https://', help_text='Enter your full website URL, eg. https://youwebsite.com ', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram_handle',
            field=models.CharField(blank=True, default='@', help_text="Enter just your handle, example, '@superbob'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter_bio_handle',
            field=models.CharField(blank=True, default='@', help_text="Enter just your handle, example, '@superbob'.", max_length=255),
        ),
    ]
