# Generated by Django 3.2.4 on 2021-06-21 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210620_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='twitter_bio_handle',
            new_name='twitter_bio',
        ),
    ]
