# Generated by Django 3.2.4 on 2021-06-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
