# Generated by Django 3.2.4 on 2021-06-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profiles-pics/default-profile-pic.jpeg', upload_to='profiles-pics'),
        ),
    ]
