# Generated by Django 3.2.4 on 2021-06-21 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210622_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='twitter_bio',
            new_name='twitter',
        ),
    ]
