# Generated by Django 3.2.4 on 2021-06-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='meta_description',
            field=models.TextField(default='meta description', max_length=160),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=60, unique=True),
        ),
    ]
