# Generated by Django 3.2.4 on 2021-06-06 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0002_auto_20210606_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='schema',
        ),
    ]
